version: 1.0.{build}
image: Visual Studio 2019


environment:
  matrix:
   - PYTHON: "C:\\Python39"

install:
    - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
    - python -m pip install requests jsonschema rfc3987 pywin32 lxml

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - call python validator_xml.py
    - call python validator_json.py
