name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Install python modules
      working-directory: 
      run: python -m pip install requests jsonschema rfc3987 pywin32

    - name: Validate json
      working-directory: 
      run: python validator.py

