name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install python modules
      working-directory: .
      run: python -m pip install requests jsonschema rfc3987 pywin32 lxml

    - name: Validate xml of UDLs folder
      working-directory: .
      run: python validator_xml.py


    - name: Validate json
      working-directory: .
      run: python validator_json.py

